import { strToU8, zipSync } from 'fflate';

export type DraftPackageJob = {
  id: string;
  workspaceId: string;
  templateId: string;
  templateCode?: string;
  templateName?: string;
  inputParams: Record<string, unknown>;
  estimatedCredits: string;
  actualCredits: string;
  renderMp4Requested: boolean;
  createdAt?: Date | string;
  completedAt?: Date | string | null;
};

export type DraftPackageStage = {
  stageCode: string;
  status: string;
  outputSnapshot?: unknown;
};

export type DraftPackageAsset = {
  assetType: string;
  storageProvider?: string | null;
  storageKey?: string | null;
  url?: string | null;
  mimeType?: string | null;
  status?: string;
  metadata?: unknown;
};

export type DraftPackageUsageRecord = {
  resourceType: string;
  provider: string;
  model?: string | null;
  usageAmount: string;
  usageUnit: string;
  creditCost: string;
};

export type DraftPackageInput = {
  job: DraftPackageJob;
  stages: DraftPackageStage[];
  assets: DraftPackageAsset[];
  usageRecords: DraftPackageUsageRecord[];
};

const encoder = new TextEncoder();

export function getDraftPackageFileName(jobId: string): string {
  return `reelflow-draft-${jobId}.zip`;
}

export function getDraftPackageStorageKey(jobId: string): string {
  return `reelflow/jobs/${jobId}/draft-package.zip`;
}

export function buildDraftPackageBuffer(input: DraftPackageInput): Buffer {
  const packageFiles = buildDraftPackageFiles(input);
  const zipped = zipSync(packageFiles, { level: 6 });
  return Buffer.from(zipped);
}

export function buildDraftPackageManifest(input: DraftPackageInput) {
  return {
    schemaVersion: 'reelflow.draft-package.v1',
    generatedAt: new Date().toISOString(),
    job: {
      id: input.job.id,
      workspaceId: input.job.workspaceId,
      templateId: input.job.templateId,
      templateCode: input.job.templateCode,
      templateName: input.job.templateName,
      estimatedCredits: input.job.estimatedCredits,
      actualCredits: input.job.actualCredits,
      renderMp4Requested: input.job.renderMp4Requested,
      createdAt: serializeDate(input.job.createdAt),
      completedAt: serializeDate(input.job.completedAt),
    },
    videoSpec: {
      width: 1080,
      height: 1920,
      fps: 30,
      format: 'jianying-draft',
    },
    files: [
      'manifest.json',
      'project.workflow.json',
      'capcut_mate_payload.json',
      'assets/asset-index.json',
      'scripts/run-capcut-mate.ps1',
      'scripts/capcut-mate-requests.http',
      'docs/capcut-mate-local-setup.md',
      'README.md',
    ],
  };
}

export function buildDraftPackageMetadata(jobId: string) {
  return {
    mode: 'local_draft',
    downloadable: true,
    fileName: getDraftPackageFileName(jobId),
    storageKey: getDraftPackageStorageKey(jobId),
    packageSchemaVersion: 'reelflow.draft-package.v1',
    adapter: 'capcut-mate',
    note: 'Generated by Reelflow local draft adapter. The package includes capcut-mate payload files for conversion.',
  };
}

function buildDraftPackageFiles(input: DraftPackageInput): Record<string, Uint8Array> {
  const manifest = buildDraftPackageManifest(input);
  const workflow = buildWorkflowProject(input);
  const payload = buildCapcutMatePayload(input, workflow);
  const assetIndex = input.assets.map((asset) => ({
    assetType: asset.assetType,
    storageProvider: asset.storageProvider,
    storageKey: asset.storageKey,
    url: asset.url,
    mimeType: asset.mimeType,
    status: asset.status,
    metadata: asset.metadata,
  }));

  return {
    'manifest.json': jsonFile(manifest),
    'project.workflow.json': jsonFile(workflow),
    'capcut_mate_payload.json': jsonFile(payload),
    'assets/asset-index.json': jsonFile(assetIndex),
    'scripts/run-capcut-mate.ps1': strToU8(buildCapcutMatePowerShellScript()),
    'scripts/capcut-mate-requests.http': strToU8(buildCapcutMateHttpFile(payload)),
    'docs/capcut-mate-local-setup.md': strToU8(buildCapcutMateSetupDoc()),
    'README.md': strToU8(buildReadme(input)),
  };
}

function buildWorkflowProject(input: DraftPackageInput) {
  const topic = stringParam(input.job.inputParams.topic) || stringParam(input.job.inputParams.claim) || 'Untitled topic';
  const tone = stringParam(input.job.inputParams.tone) || 'clear';
  const audience = stringParam(input.job.inputParams.audience) || 'general audience';
  const examples = stringParam(input.job.inputParams.examples);
  const durationSeconds = 45;

  const scenes = [
    {
      id: 'hook',
      title: 'Opening hook',
      startMs: 0,
      endMs: 8000,
      narration: `Here is a ${tone} opening for ${audience}: ${topic}.`,
      visualPrompt: `Simple vertical short-video opening scene about ${topic}.`,
    },
    {
      id: 'body',
      title: 'Main explanation',
      startMs: 8000,
      endMs: 35000,
      narration: examples ? `Use this example as supporting material: ${examples}` : `Explain the idea in plain language: ${topic}.`,
      visualPrompt: `Structured explainer visuals, clean composition, mobile-first frame.`,
    },
    {
      id: 'close',
      title: 'Closing note',
      startMs: 35000,
      endMs: durationSeconds * 1000,
      narration: `Close with one actionable takeaway for ${audience}.`,
      visualPrompt: `Concise closing frame with strong contrast and readable composition.`,
    },
  ];

  return {
    schemaVersion: 'reelflow.workflow-project.v1',
    canvas: {
      width: 1080,
      height: 1920,
      fps: 30,
    },
    topic,
    tone,
    audience,
    durationMs: durationSeconds * 1000,
    scenes,
    stages: input.stages.map((stage) => ({
      code: stage.stageCode,
      status: stage.status,
      outputSnapshot: stage.outputSnapshot,
    })),
    usage: input.usageRecords,
  };
}

export function buildCapcutMatePayload(input: DraftPackageInput, workflow: ReturnType<typeof buildWorkflowProject>) {
  const captions = workflow.scenes.map((scene) => ({
    start: scene.startMs * 1000,
    end: scene.endMs * 1000,
    text: scene.narration,
    font_size: 13,
  }));

  return {
    adapter: 'capcut-mate',
    adapterVersion: 'capcut-mate.openapi.v1',
    defaultBaseUrl: 'http://localhost:30000',
    baseUrlEnv: 'CAPCUT_MATE_BASE_URL',
    source: {
      project: 'Reelflow',
      jobId: input.job.id,
      templateCode: input.job.templateCode,
      templateName: input.job.templateName,
    },
    requirements: [
      'Start a capcut-mate service before running the request script.',
      'The service exposes /openapi/capcut-mate/v1/create_draft, /add_captions, and /save_draft.',
      'The current MVP package writes captions and the normalized workflow project. Real image/audio files can be added after provider assets are connected.',
    ],
    steps: [
      {
        id: 'create_draft',
        description: 'Create a vertical 1080x1920 Jianying draft.',
        method: 'POST',
        path: '/openapi/capcut-mate/v1/create_draft',
        captures: {
          draftUrl: 'draft_url',
        },
        body: {
          width: workflow.canvas.width,
          height: workflow.canvas.height,
        },
      },
      {
        id: 'add_captions',
        description: 'Add generated narration as timeline captions.',
        method: 'POST',
        path: '/openapi/capcut-mate/v1/add_captions',
        dependsOn: 'create_draft',
        body: {
          draft_url: '{{draft_url}}',
          captions: JSON.stringify(captions),
          text_color: '#ffffff',
          border_color: '#111111',
          alignment: 1,
          font_size: 13,
          transform_y: 720,
        },
      },
      {
        id: 'save_draft',
        description: 'Persist the generated draft after all editing operations.',
        method: 'POST',
        path: '/openapi/capcut-mate/v1/save_draft',
        dependsOn: 'add_captions',
        body: {
          draft_url: '{{draft_url}}',
        },
      },
    ],
    notes: [
      'The first step returns draft_url. Substitute it into later steps.',
      'Image and audio provider outputs can be appended as add_images and add_audios steps when real assets are available.',
      'For local Windows verification, run scripts/run-capcut-mate.ps1 after starting capcut-mate.',
    ],
  };
}

function buildReadme(input: DraftPackageInput): string {
  return [
    '# Reelflow Draft Package',
    '',
    `Job ID: ${input.job.id}`,
    `Template: ${input.job.templateName ?? input.job.templateCode ?? input.job.templateId}`,
    '',
    'This package contains Reelflow workflow data and a capcut-mate payload.',
    '',
    'Files:',
    '- manifest.json: package metadata',
    '- project.workflow.json: normalized Reelflow video project',
    '- capcut_mate_payload.json: HTTP steps for capcut-mate draft generation',
    '- assets/asset-index.json: assets recorded for this job',
    '- scripts/run-capcut-mate.ps1: Windows helper script that calls a local capcut-mate service',
    '- scripts/capcut-mate-requests.http: request collection for manual API verification',
    '- docs/capcut-mate-local-setup.md: local service setup notes',
    '',
    'Quick local conversion:',
    '1. Start capcut-mate locally on http://localhost:30000.',
    '2. Extract this zip package.',
    '3. Run: powershell -ExecutionPolicy Bypass -File scripts/run-capcut-mate.ps1',
    '4. Open the returned draft_url in the capcut-mate client or API workflow.',
    '',
    'Current MVP limitation:',
    '- The package produces a draft with generated captions and a normalized workflow project.',
    '- Image and audio tracks are represented as trace assets until real media providers are connected.',
    '',
  ].join('\n');
}

function buildCapcutMatePowerShellScript(): string {
  return [
    'param(',
    '  [string]$BaseUrl = $env:CAPCUT_MATE_BASE_URL',
    ')',
    '',
    'if ([string]::IsNullOrWhiteSpace($BaseUrl)) {',
    '  $BaseUrl = "http://localhost:30000"',
    '}',
    '',
    '$PayloadPath = Join-Path $PSScriptRoot "..\\capcut_mate_payload.json"',
    'if (!(Test-Path -LiteralPath $PayloadPath)) {',
    '  throw "capcut_mate_payload.json was not found next to the scripts folder."',
    '}',
    '',
    '$Payload = Get-Content -LiteralPath $PayloadPath -Raw | ConvertFrom-Json',
    '$DraftUrl = $null',
    '',
    'foreach ($Step in $Payload.steps) {',
    '  $Body = $Step.body | ConvertTo-Json -Depth 20 -Compress',
    '  if ($DraftUrl) {',
    '    $Body = $Body.Replace("{{draft_url}}", $DraftUrl)',
    '  }',
    '',
    '  $Uri = $BaseUrl.TrimEnd("/") + $Step.path',
    '  Write-Host ("Running " + $Step.id + " -> " + $Uri)',
    '  $Response = Invoke-RestMethod -Method $Step.method -Uri $Uri -ContentType "application/json" -Body $Body',
    '',
    '  if ($Response.draft_url) {',
    '    $DraftUrl = [string]$Response.draft_url',
    '  }',
    '}',
    '',
    'if (!$DraftUrl) {',
    '  throw "capcut-mate did not return a draft_url."',
    '}',
    '',
    'Write-Host ""',
    'Write-Host "Draft URL:"',
    'Write-Host $DraftUrl',
    '',
  ].join('\n');
}

function buildCapcutMateHttpFile(payload: ReturnType<typeof buildCapcutMatePayload>): string {
  const createDraft = payload.steps.find((step) => step.id === 'create_draft')?.body;
  const addCaptions = payload.steps.find((step) => step.id === 'add_captions')?.body;
  const saveDraft = payload.steps.find((step) => step.id === 'save_draft')?.body;

  return [
    '@baseUrl = http://localhost:30000',
    '@draftUrl = replace_with_create_draft_response_draft_url',
    '',
    '### Create draft',
    'POST {{baseUrl}}/openapi/capcut-mate/v1/create_draft',
    'Content-Type: application/json',
    '',
    JSON.stringify(createDraft, null, 2),
    '',
    '### Add captions',
    'POST {{baseUrl}}/openapi/capcut-mate/v1/add_captions',
    'Content-Type: application/json',
    '',
    JSON.stringify(addCaptions, null, 2),
    '',
    '### Save draft',
    'POST {{baseUrl}}/openapi/capcut-mate/v1/save_draft',
    'Content-Type: application/json',
    '',
    JSON.stringify(saveDraft, null, 2),
    '',
  ].join('\n');
}

function buildCapcutMateSetupDoc(): string {
  return [
    '# capcut-mate local setup',
    '',
    'Reelflow uses capcut-mate as the local Jianying draft materialization adapter.',
    '',
    '## Start service',
    '',
    'Option A: Docker Compose from the capcut-mate repository:',
    '',
    '```powershell',
    'git clone https://github.com/Hommy-master/capcut-mate.git',
    'cd capcut-mate',
    'docker-compose pull',
    'docker-compose up -d',
    '```',
    '',
    'Option B: Python runtime from the capcut-mate repository:',
    '',
    '```powershell',
    'git clone https://github.com/Hommy-master/capcut-mate.git',
    'cd capcut-mate',
    'uv sync',
    'uv pip install -e .[windows]',
    'uv run main.py',
    '```',
    '',
    'The default API address is http://localhost:30000.',
    '',
    '## Run this draft package',
    '',
    'Extract the Reelflow zip package, then run:',
    '',
    '```powershell',
    'powershell -ExecutionPolicy Bypass -File scripts/run-capcut-mate.ps1',
    '```',
    '',
    'If your service runs elsewhere:',
    '',
    '```powershell',
    '$env:CAPCUT_MATE_BASE_URL = "http://localhost:30000"',
    'powershell -ExecutionPolicy Bypass -File scripts/run-capcut-mate.ps1',
    '```',
    '',
    'The script prints the final draft_url returned by capcut-mate.',
    '',
  ].join('\n');
}

function jsonFile(value: unknown): Uint8Array {
  return encoder.encode(`${JSON.stringify(value, null, 2)}\n`);
}

function serializeDate(value: Date | string | null | undefined): string | null {
  if (!value) return null;
  return value instanceof Date ? value.toISOString() : value;
}

function stringParam(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}
